//
// Created by kon on 22.03.18.
//

#ifndef DPREEN_SEGMENTATION_GLOBALCONSTANTS_H
#define DPREEN_SEGMENTATION_GLOBALCONSTANTS_H

#define MAX_SCALE 3
#define MAX_K 6

#endif //DPREEN_SEGMENTATION_GLOBALCONSTANTS_H
